[pytest]
addopts = -p no:warnings -s -vv
filterwarnings = ignore:Module already imported:pytest.PytestWarning
markers =
    Mallinstance: Marks tests for Mallinstance
    User: Marks tests for User
    recharge: Marks tests for recharge

